package khvatid.shop.ui.theme

import androidx.compose.ui.graphics.Color


val  theme_light_primary = Color(0xFF474ED0)
val  theme_light_onPrimary = Color(0xFFFFFFFF)
val  theme_light_primaryContainer = Color(0xFFE0E0FF)
val  theme_light_onPrimaryContainer = Color(0xFF01006E)
val  theme_light_secondary = Color(0xFF5455A9)
val  theme_light_onSecondary = Color(0xFFFFFFFF)
val  theme_light_secondaryContainer = Color(0xFFE1DFFF)
val  theme_light_onSecondaryContainer = Color(0xFF0B0664)
val  theme_light_tertiary = Color(0xFF5655A8)
val  theme_light_onTertiary = Color(0xFFFFFFFF)
val  theme_light_tertiaryContainer = Color(0xFFE2DFFF)
val  theme_light_onTertiaryContainer = Color(0xFF0F0564)
val  theme_light_error = Color(0xFFBA1A1A)
val  theme_light_errorContainer = Color(0xFFFFDAD6)
val  theme_light_onError = Color(0xFFFFFFFF)
val  theme_light_onErrorContainer = Color(0xFF410002)
val  theme_light_background = Color(0xFFFFFBFF)
val  theme_light_onBackground = Color(0xFF1B1B1F)
val  theme_light_surface = Color(0xFFFFFBFF)
val  theme_light_onSurface = Color(0xFF1B1B1F)
val  theme_light_surfaceVariant = Color(0xFFE4E1EC)
val  theme_light_onSurfaceVariant = Color(0xFF46464F)
val  theme_light_outline = Color(0xFF777680)
val  theme_light_inverseOnSurface = Color(0xFFF3EFF4)
val  theme_light_inverseSurface = Color(0xFF303034)
val  theme_light_inversePrimary = Color(0xFFBFC2FF)
val  theme_light_shadow = Color(0xFF000000)
val  theme_light_surfaceTint = Color(0xFF474ED0)
val  theme_light_outlineVariant = Color(0xFFC7C5D0)
val  theme_light_scrim = Color(0xFF000000)

val  theme_dark_primary = Color(0xFFBFC2FF)
val  theme_dark_onPrimary = Color(0xFF0C0CA3)
val  theme_dark_primaryContainer = Color(0xFF2C32B7)
val  theme_dark_onPrimaryContainer = Color(0xFFE0E0FF)
val  theme_dark_secondary = Color(0xFFC1C1FF)
val  theme_dark_onSecondary = Color(0xFF242478)
val  theme_dark_secondaryContainer = Color(0xFF3C3D8F)
val  theme_dark_onSecondaryContainer = Color(0xFFE1DFFF)
val  theme_dark_tertiary = Color(0xFFC2C1FF)
val  theme_dark_onTertiary = Color(0xFF262377)
val  theme_dark_tertiaryContainer = Color(0xFF3E3C8F)
val  theme_dark_onTertiaryContainer = Color(0xFFE2DFFF)
val  theme_dark_error = Color(0xFFFFB4AB)
val  theme_dark_errorContainer = Color(0xFF93000A)
val  theme_dark_onError = Color(0xFF690005)
val  theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val  theme_dark_background = Color(0xFF1B1B1F)
val  theme_dark_onBackground = Color(0xFFE5E1E6)
val  theme_dark_surface = Color(0xFF1B1B1F)
val  theme_dark_onSurface = Color(0xFFE5E1E6)
val  theme_dark_surfaceVariant = Color(0xFF46464F)
val  theme_dark_onSurfaceVariant = Color(0xFFC7C5D0)
val  theme_dark_outline = Color(0xFF918F9A)
val  theme_dark_inverseOnSurface = Color(0xFF1B1B1F)
val  theme_dark_inverseSurface = Color(0xFFE5E1E6)
val  theme_dark_inversePrimary = Color(0xFF474ED0)
val  theme_dark_shadow = Color(0xFF000000)
val  theme_dark_surfaceTint = Color(0xFFBFC2FF)
val  theme_dark_outlineVariant = Color(0xFF46464F)
val  theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF4E55D7)